services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8080"
    environment:
      - DOZZLE_LEVEL=info

  influxdb:
    image: influxdb:2-alpine
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=smart-home
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2

  smart-home-db:
    image: postgres:17-alpine
    container_name: smart-home-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=smarthome
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  smart-home-app:
    image: smart-home-app:latest
    container_name: smart-home-app
    restart: always
    depends_on:
      - smart-home-db
      - influxdb
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=${DB_JDBC_URL}
      - QUARKUS_DATASOURCE_REACTIVE_URL=${DB_REACTIVE_URL}
      - QUARKUS_DATASOURCE_USERNAME=${DB_USERNAME}
      - QUARKUS_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - QUARKUS_FLYWAY_MIGRATE_AT_START=true
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUX_TOKEN}
      - INFLUXDB_ORG=smart-home
      - INFLUXDB_BUCKET=telemetry

  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    user: "1000:1000"
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - /home/jakub/smart-home-data/mosquitto/config:/mosquitto/config
      - /home/jakub/smart-home-data/mosquitto/data:/mosquitto/data
      - /home/jakub/smart-home-data/mosquitto/log:/mosquitto/log

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: always
    volumes:
      - /home/jakub/smart-home-data/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "8082:8080"
    environment:
      - TZ=Europe/Prague
    devices:
      - /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_6252cfa022f4ef119d04bb1b6d9880ab-if00-port0:/dev/ttyACM0
    depends_on:
      - mqtt-broker

volumes:
  db_data:
  influxdb_data: