# --- SPOLEČNÁ KONFIGURACE ---
quarkus:
  http:
    port: 8080
  log:
    level: INFO
    console:
      format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"

  # Databáze (Postgres)
  datasource:
    db-kind: postgresql

  # Flyway migrace
  flyway:
    migrate-at-start: ${QUARKUS_FLYWAY_MIGRATE_AT_START:true}
    locations: db/migration
    baseline-on-migrate: true

# InfluxDB konfigurace
influxdb:
  url: ${INFLUX_URL}
  token: ${INFLUX_TOKEN}
  org: ${INFLUX_ORG}
  bucket: ${INFLUX_BUCKET}

# Reactive Messaging (MQTT)
mp:
  messaging:
    connector:
      smallrye-mqtt:
        host: ${MQTT_HOST:mqtt-broker}
        port: ${MQTT_PORT:1883}
        max-message-size: 1048576
        reconnect-attempts: -1
        reconnect-interval-seconds: 5
        keep-alive-seconds: 60
        auto-keep-alive: true
    incoming:
      z2m-devices:
        connector: smallrye-mqtt
        topic: zigbee2mqtt/bridge/devices
        qos: 1
        client-id: smart-home-core-devices
        failure-strategy: ignore

      z2m-bridge:
        connector: smallrye-mqtt
        topic: zigbee2mqtt/bridge/state
        qos: 0
        client-id: smart-home-core-bridge
        failure-strategy: ignore

      z2m-telemetry:
        connector: smallrye-mqtt
        topic: zigbee2mqtt/+
        qos: 0
        client-id: smart-home-core-telemetry
        failure-strategy: ignore