name: Deploy to Pi 5
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Clean workspace
        run: sudo rm -rf mosquitto zigbee2mqtt

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests and Maven Build
        run: mvn clean package

      - name: Docker build and deploy
        run: |
          docker build -t smart-home-app:latest .
          docker compose --env-file /home/jakub/.env up -d